export const ASYNC_GET_COUNTRIES_DATA_START = 'ASYNC_GET_COUNTRIES_DATA_START';
export const ASYNC_GET_COUNTRIES_DATA_END = 'ASYNC_GET_COUNTRIES_DATA_END';
export const ASYNC_GET_COUNTRIES_DATA_ERROR = 'ASYNC_GET_COUNTRIES_DATA_ERROR';
export const UPDATE_SEARCH_VALUE = 'UPDATE_SEARCH_VALUE';
export const UPDATE_SELECT_FILTER = 'UPDATE_SELECT_FILTER';
export const SWITCH_THEME = 'SWITCH_THEME';
export const CHECK_SAVED_THEME = 'CHECK_SAVED_THEME';
